### ISSUE TITLE
Detecting deployment mode properly

### ISSUE THREAD

**Issue by jissereitsma** [extdn/installer-m2#1]
Currently, the `MAGE_MODE` environment variable is used for detecting the current mode (if I'm not mistaken). In my personal environments, I don't use this variable but simply rely on the right variable in `app/etc/env.php`.

**Comment by fooman** [comment]
We should be good. A bit of a double up of terms.

I am reading `app/etc/env.php` into env here
https://github.com/extdn/installer-m2/blob/master/extdn_installer.php#L176
and then check it here for example https://github.com/extdn/installer-m2/blob/master/extdn_installer.php#L262
