### ISSUE TITLE
Magento project check fails

### ISSUE THREAD

**Issue by chikoi** [extdn/installer-m2#12]
I get this error
 
[ExtDN\Task\CheckComposerIssues] Checking for supported Magento projects
**[ExtDN\Task\CheckComposerIssues]  This does not look like a supported Magento project.**
[ExtDN\Task\CheckComposerIssues]  Exit code 1
[notice] Stopping on fail. Exiting....

because my composer.json does not have these
https://github.com/extdn/installer-m2/blob/4087a50fcff89000bc838b8683d74eab77d53f9c/src/Task/CheckComposerIssues.php#L71-L75

Steps to replicate:
1. Install Magento 2 from https://github.com/magento/magento2
2. Install an extension
`sh -ic "$(curl -sS https://raw.githubusercontent.com/extdn/installer-m2/master/bin/oneliner.sh)" -- install fooman/printorderpdf-m2:^3.0`

**Comment by fooman** [comment]
Thanks @chikoi - does it have this line https://github.com/magento/magento2/blob/2.4-develop/composer.json#L2 ?

**Comment by chikoi** [comment]
@fooman yes, it does have that line

**Comment by fooman** [comment]
Great - do you mind checking with the latest release.

```
extdn_installer.phar self:update
extdn_installer.phar install fooman/printorderpdf-m2:^3.0
```

**Comment by chikoi** [comment]
That fixed it!
